# Generated by Django 2.0 on 2022-04-09 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazva', models.CharField(max_length=200, verbose_name='Назва')),
                ('mova', models.CharField(max_length=20, verbose_name='Мова')),
            ],
        ),
    ]
