# Generated by Django 2.0 on 2022-04-09 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='anotation',
            field=models.TextField(default=1, verbose_name='Анотація'),
            preserve_default=False,
        ),
    ]
