# Generated by Django 2.1.5 on 2022-04-16 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20220416_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Автор', to='books.Autor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='gangre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Жанр', to='books.Gangre'),
            preserve_default=False,
        ),
    ]
